version: "3.9"

services:
  db:
    image: postgres:15.0-alpine
    container_name: diario_sono_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diario_sono
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    networks:
      - diario_sono_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d diario_sono -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: diario_sono_backend
    ports:
      - "3035:3035"
    environment:
      FLASK_RUN_PORT: 3035
      FLASK_RUN_HOST: 0.0.0.0
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: diario_sono
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - diario_sono_net

  frontend:
    build:
      context: ./frontend
    container_name: diario_sono_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3035
    depends_on:
      - backend
    networks:
      - diario_sono_net

networks:
  diario_sono_net:
    driver: bridge
